#!/usr/bin/env python3
"""Emit lib/core/icons/wiz_icon_data.dart from the ICONS map in the design bundle."""
import re, pathlib

root = pathlib.Path(__file__).resolve().parents[1]
bundle = (root / 'design/reference/_ds_bundle.js').read_text()
block = re.search(r"const ICONS = \{(.*?)\n\};", bundle, re.S).group(1)
entries = re.findall(r"'([a-z0-9-]+)': '<path d=\"([^\"]+)\"></path>'", block)
assert len(entries) == 49, len(entries)

def camel(name):
    head, *rest = name.split('-')
    return head + ''.join(p.capitalize() for p in rest)

out = ["// GENERATED by tool/gen_icons.py from design/reference/_ds_bundle.js.",
       "// Regenerate with: python3 tool/gen_icons.py && dart format lib/core/icons",
       "// Phosphor Bold glyphs (256 grid) under WizCtl names. Do not edit by hand.",
       "// Exempt from the ~300-line file guideline: this is generated data, one",
       "// constant per glyph, not hand-maintained code.",
       "",
       "/// One Phosphor Bold glyph: its WizCtl name and SVG path data on a 256 grid.",
       "class WizIconData {",
       "  final String name;",
       "  final String path;",
       "  const WizIconData(this.name, this.path);",
       "}",
       "",
       "/// The 49 glyphs the design system uses.",
       "class WizIcons {",
       "  WizIcons._();",
       ""]
for name, path in entries:
    out.append(f"  static const WizIconData {camel(name)} = WizIconData('{name}', '{path}');")
out.append("")
out.append("  static const List<WizIconData> all = [")
for name, _ in entries:
    out.append(f"    {camel(name)},")
out.append("  ];")
out.append("")
out.append("  static WizIconData? byName(String name) {")
out.append("    for (var icon in all) {")
out.append("      if (icon.name == name) return icon;")
out.append("    }")
out.append("    return null;")
out.append("  }")
out.append("}")
(root / 'lib/core/icons').mkdir(parents=True, exist_ok=True)
(root / 'lib/core/icons/wiz_icon_data.dart').write_text("\n".join(out) + "\n")
print(f"wrote {len(entries)} icons")
